# Generated by Django 5.1.4 on 2024-12-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
