# Generated by Django 5.1.4 on 2024-12-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookman', '0002_alter_book_isbn_number_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
