# Generated by Django 5.1.4 on 2024-12-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookman', '0006_alter_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
