# Generated by Django 5.1.4 on 2024-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookman', '0007_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
